### PR TITLE
Ember 2.0 compatibility

### PR DESCRIPTION
**Pull request by mukk85**
Updated code and fixed all deprecation notices for socket connection on ember-data 2.0.0-beta.2

### CODE REVIEW

**Comment by huafu** [comment]
Thanks a lot, but can you revert the changes you made in package.json please

**Comment by mukk85** [comment]
Committed this code to our other PR.

**Comment by huafu** [comment]
I don't see any other PR from you

**Comment by huafu** [comment]
Oh sorry it is not "exactly" from you ok, thanks. I'll have a look in my tomorrow morning (few hours from now). Again, thanks!

**Pull request closed without merging**
